export const mockDataPets = [
    {
        id: 1,
        name: "Furia",
        type: "dog",
        sex: "male",
        size: "medium",
        photo: "https://upload.wikimedia.org/wikipedia/commons/5/56/IdealGPBY.jpg",
        vaccinated: true,
        deworming: true,
        sterilized: true,
        breed: "Doberman Pinscher",
        email: "olga.moreno@example.com",
        description: "",
        weight: 12,
        age: 3,
        phone: 123423455345,
        available: true,
        adopted: false,
    },
    {
        id: 2,
        name: "Brandy",
        type: "dog",
        sex: "female",
        age: 4,
        size: "small",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Racib%C3%B3rz_2007_082.jpg/1280px-Racib%C3%B3rz_2007_082.jpg",
        weight: 3,
        vaccinated: true,
        deworming: true,
        sterilized: false,
        breed: "French Bulldog",
        email: "nadja.raden@example.com",
        phone: 23454356346,
        available: true,
        description: "",
        adopted: false,
    },
    {
        name: "Cristal",
        id: 3,
        type: "dog",
        sex: "female",
        age: 5,
        size: "large",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Weimaraner_hembra.jpg/800px-Weimaraner_hembra.jpg",
        weight: 12,
        vaccinated: true,
        deworming: true,
        sterilized: true,
        breed: "Bracco Italiano",
        email: "deepika.rai@example.com",
        phone: 123423455345,
        available: true,
        description: "Muy cariñosa y obediente",
        adopted: false,
    },
    {
        id: 4,
        name: "Luna",
        type: "dog",
        sex: "female",
        age: 0,
        size: "medium",
        photo: "https://www.diariodesevilla.es/2023/02/22/sociedad/Shiba-Inu-perros-buscados_1768633150_177677206_667x375.jpg",
        weight: 8,
        vaccinated: true,
        deworming: true,
        sterilized: true,
        breed: "Shiba Inu",
        email: "ehrenfried.daum@example.com",
        phone: 3245345345,
        available: true,
        description: "",
        adopted: false,
    },
    {
        id: 5,
        name: "Dracco",
        type: "dog",
        sex: "male",
        age: 0,
        size: "small",
        photo: "https://smylepets.com/wp-content/uploads/2021/03/Beagle.png.webp",
        weight: 4,
        vaccinated: true,
        deworming: true,
        sterilized: true,
        breed: "Beagle",
        email: "gulhan.feitsma@example.com",
        phone: 4567853256,
        available: true,
        description: "",
        adopted: false,
    },
    {
        id: 6,
        name: "Menchu",
        type: "cat",
        sex: "female",
        age: 3,
        size: "small",
        photo: "https://fotografias.lasexta.com/clipping/cmsimages02/2019/01/25/DB41B993-B4C4-4E95-8B01-C445B8544E8E/98.jpg?crop=4156,2338,x0,y219&width=1900&height=1069&optimize=high&format=webply",
        weight: 2,
        vaccinated: false,
        deworming: false,
        sterilized: true,
        breed: "Siamese",
        email: "ehrenfried.daum@example.com",
        phone: 23454356346,
        available: true,
        description: "",
        adopted: false,
    },
    {
        id: 7,
        name: "Firulais",
        type: "cat",
        sex: "female",
        age: 2,
        size: "medium",
        photo: "https://i.pinimg.com/originals/7f/1e/9a/7f1e9a7a2e9307897e3ad0bea0ef5a4f.jpg",
        weight: 0,
        vaccinated: false,
        deworming: false,
        sterilized: false,
        breed: "Siberian",
        email: "dragomir.bozhenko@example.com",
        phone: 12243252345,
        available: true,
        description: "",
        adopted: false,
    },
    {
        id: 8,
        name: "Richar",
        type: "cat",
        sex: "male",
        age: 1,
        size: "medium",
        photo: "https://www.mundogato.net/wp-content/uploads/nombres-para-gatos-bombay-1200x845.jpg",
        weight: 4,
        vaccinated: false,
        deworming: true,
        sterilized: true,
        breed: "Bombay",
        email: "ehrenfried.daum@example.com",
        phone: 1242345643,
        available: true,
        description: "",
        adopted: false,
    },
    {
        id: 9,
        name: "Misu",
        type: "cat",
        sex: "male",
        size: "medium",
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Gata_com%C3%BAn_negra.png/360px-Gata_com%C3%BAn_negra.png",
        vaccinated: true,
        deworming: true,
        sterilized: false,
        breed: "Bombay",
        email: "ehrenfried.daum@example.com",
        description: "",
        weight: 3,
        age: 2,
        available: true,
        phone: 32355345,
        adopted: false,
    },
    {
        id: 10,
        name: "Rubi",
        type: "cat",
        sex: "female",
        size: "medium",
        photo: "https://t1.ea.ltmcdn.com/es/razas/3/9/1/gato-balines_193_0_600.jpg",
        vaccinated: true,
        deworming: true,
        sterilized: false,
        breed: "Balinese",
        email: "daniela.carrera@example.com",
        description: "",
        age: 3,
        phone: 234234234234,
        available: true,
        weight: 2,
        adopted: false,
    },
    {
        id: 11,
        name: "lala",
        type: "dog",
        sex: "male",
        size: "large",
        photo: "https://www.hola.com/imagenes/estar-bien/20191004150785/pastor-aleman-raza-de-perro-caracteristicas/0-728-57/raza-de-perro-pastor-aleman-e.jpg",
        vaccinated: true,
        deworming: false,
        sterilized: false,
        breed: "Akbash Dog",
        email: "isamadridmora@gmail.con",
        description:
            "manchas y le gusta el origami y es inteligente y es lindo",
        available: true,
        weight: 12,
        age: 3,
        phone: 199467,
        adopted: false,
    },
];
